# For more info on HTTP files go to https://aka.ms/vs/httpfile

@TrainingManagement.WebAPI_HostAddress = http://localhost:5123

### Login
POST {{TrainingManagement.WebAPI_HostAddress}}/api/v1/auth
Content-Type: application/json

{
  "userName": "Admin@WIMASMC.com",
  "password": "AdminWIMASMC@123"
}

### Refresh Token
POST {{TrainingManagement.WebAPI_HostAddress}}/api/auth/refresh
Content-Type: application/json

{
  "token": "{{access_token}}",
  "refreshToken": "{{refresh_token}}"
}


### Validate Token
